# Conda environment setup for ARIA-tools
name: ARIA-tools
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python>=3.10

  # Geospatial & scientific libraries
  - affine
  - arm_pyart
  - dask
  - dem_stitcher>=2.5.8
  - gdal>=3.7.0
  - h5py
  - joblib
  - libgdal-hdf5
  - libgdal-netcdf
  - matplotlib
  - netcdf4
  - numpy>=1.24.*
  - pandas
  - pip
  - pyproj
  - pytest
  - python-dateutil
  - rasterio>=1.3.*
  - rioxarray
  - requests
  - scipy>=1.11.*
  - shapely
  - xarray
